config/routes.rb
TODO::Application.routes.draw do

  root :to => 'home#index'

  get 'perfil', to: 'users#show', as: 'show'
  get 'registrarse', to: 'users#new', as: 'signup'
  get 'entrar', to: 'sessions#new', as: 'login'
  delete 'salir', to: 'sessions#destroy', as: 'logout'

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create]
  resources :tasks, :only => [:index, :new, :create, :show] do
    resources :completions, :only => [:create]
  end
  resources :assignments, :only => [:index, :new, :create]

  namespace :api do
    namespace :v1 do
      resources :tasks
    end
  end

  get '*a', :to => 'errors#routing'
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_access_token

private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
      self.expires_at = 5.minutes.from_now
    end while self.class.exists?(access_token: access_token)
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :resource
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :text, :completed, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, uniqueness: true
  validates :email, presence: true
  validates :password, length: { in: 4..8 }

  attr_accessible :email, :firstname, :lastname, :password, :password_confirmation
  def has_notifications?
    false
  end

  def has_email?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end


private
  def current_user

    #if session[:user_id]
    #  if user = User.find(session[:user_id])
    #    @current_user ||= user
    #  else
    #    redirect_to root_path
    #  end
    #else

    #end
    @current_user ||= User.find(session[:user_id]) if session[:user_id]

    rescue ActiveRecord::RecordNotFound
      session[:user_id] = nil
      flash[:notice] = "Su sesió+n expiró"
      redirect_to root_path

  end
  helper_method :current_user

  def authorize
    redirect_to login_url if current_user.nil?
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def index

  end
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  before_filter :authorize

  def create
    Task.find(params[:task_id]).touch(:completed_at)

    redirect_to tasks_path
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def routing
    logger.error "Error de ruteo ( [#{request.method}] #{request.url} )"
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authorize

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  layout "layouts/login"

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Bienvenido!"
    else
      flash.now.alert = "Email o Password invalido"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Adios!"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authorize

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "Task successfully created"
      redirect_to tasks_path
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def show
    @task = Task.find(params[:id])
  end

private

  def task_params
    params.require(:task).permit(:text, :completed, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "layouts/login"

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Gracias por registrarse"
    else
      render "new"
    end
  end

  def show
    @user = User.find(session[:user_id])
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :firstname, :lastname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/count_helper.rb
module CountHelper
  def count_tasks
    @task_count ||= Task.where("completed_at IS NOT NULL").count
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/title_helper.rb
module TitleHelper
  def page_title
    #t page_title_translation_key,
    #  page_title_context.merge(:default => :"title.default")
    "#{t :"title.default" } :: #{t page_title_translation_key}"
  end

  def section_title
    t page_title_translation_key
  end

  def page_title_translation_key
    :"title.#{controller_name}.#{action_name}"
  end

  def page_title_context
    controller.view_assigns.symbolize_keys
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div class="col-md-12 col-sm-12">
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  </div>
  <% end %>
<% end %>

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if current_user %>
  <li><%= link_to "Mi Perfil", show_path %></li>
  <li class="divider"></li>
  <li><a data-method="delete" href="<%= url_for logout_path %>"><i class="fa fa-power-off"></i>&nbsp;&nbsp;Salir</a></li>
<% else %>
  <li><%= link_to "Sign Up", signup_path %></li>
  <li><%= link_to "Sign In", login_path %></li>
<% end %>

app/views/layouts/_sidebar.html.erb
<!-- BEGIN SIDEBAR -->
  <!-- BEGIN MENU -->
  <div class="page-sidebar" id="main-menu">
      <div class="page-sidebar-wrapper" id="main-menu-wrapper">
    <!-- BEGIN MINI-PROFILE -->
    <div class="user-info-wrapper">
      <div class="profile-wrapper">
        <!--<img src="/assets/profiles/avatar.jpg" alt="" data-src="/assets/profiles/avatar.jpg" data-src-retina="/assets/profiles/avatar2x.jpg" width="69" height="69" />-->
        <img src="<%= avatar_url(current_user) %>" alt="" data-src="<%= avatar_url(current_user) %>" data-src-retina="<%= avatar_url(current_user) %>" width="69" height="69" />
      </div>
      <div class="user-info">
        <div class="greeting">Welcome</div>
        <div class="username"><%= current_user.firstname %> <span class="semi-bold"><%= current_user.lastname %></span></div>
        <div class="status">Status<a href="#"><div class="status-icon green"></div>Online</a></div>
      </div>
    </div>
    <!-- END MINI-PROFILE -->
    <!-- BEGIN SIDEBAR MENU -->
    <p class="menu-title">BROWSE<span class="pull-right"><a href="javascript:;"><i class="fa fa-refresh"></i></a></span></p>
    <ul>
      <!-- BEGIN SELECTED LINK -->
      <li class="start active">
        <a href="<%= url_for root_path %>">
          <i class="icon-custom-home"></i>
          <span class="title">Inicio</span>
          <span class="selected"></span>
          <!--<span class="badge badge-important pull-right">5</span>-->
        </a>
      </li>
      <!-- END SELECTED LINK -->
      <!-- BEGIN BADGE LINK -->
      <li class="">
        <a href="<%= url_for tasks_path %>">
          <i class="fa fa-envelope"></i>
          <span class="title">Tareas</span>
          <% if count_tasks > 0 %>
            <span class="badge badge-disable pull-right"><%= count_tasks %></span>
          <% end %>
        </a>
      </li>
      <!-- END BADGE LINK -->
      <!-- BEGIN SINGLE LINK -->
      <li class="">
        <a href="<%= url_for assignments_path %>">
          <i class="fa fa-flag"></i>
          <span class="title">Turnos</span>
        </a>
      </li>
      <!-- END SINGLE LINK -->
      <!-- BEGIN ONE LEVEL MENU -->
      <li class="">
        <a href="javascript:;">
          <i class="icon-custom-ui"></i>
          <span class="title">Link 4</span>
          <span class="arrow"></span>
        </a>
        <ul class="sub-menu">
          <li><a href="#">Sub Link 1</a></li>
        </ul>
      </li>
      <!-- END ONE LEVEL MENU -->
      <!-- BEGIN TWO LEVEL MENU -->
      <li class="">
        <a href="javascript:;">
          <i class="fa fa-folder-open"></i>
          <span class="title">Link 5</span>
          <span class="arrow"></span>
        </a>
        <ul class="sub-menu">
          <li><a href="javascript:;">Sub Link 1</a></li>
          <li>
            <a href="javascript:;"><span class="title">Sub Link 2</span><span class="arrow "></span></a>
            <ul class="sub-menu">
              <li><a href="javascript:;">Sub Link 1</a></li>
            </ul>
          </li>
        </ul>
      </li>
      <!-- END TWO LEVEL MENU -->
    </ul>
    <!-- END SIDEBAR MENU -->
    <!-- BEGIN SIDEBAR WIDGETS -->
    <div class="side-bar-widgets">
      <!-- BEGIN FOLDER WIDGET -->
      <p class="menu-title">FOLDER<span class="pull-right"><a href="#" class="create-folder"><i class="icon-plus"></i></a></span></p>
      <ul class="folders">
        <li><a href="#"><div class="status-icon green"></div>Task 1</a></li>
        <!-- BEGIN HIDDEN INPUT BOX (FOR ADD FOLDER LINK) -->
        <li class="folder-input" style="display:none">
          <input type="text" placeholder="Name of folder" class="no-boarder folder-name" name="" id="folder-name">
        </li>
        <!-- END HIDDEN INPUT BOX (FOR ADD FOLDER LINK) -->
      </ul>
      <!-- END FOLDER WIDGET -->
      <!-- BEGIN PROJECTS WIDGET -->
      <p class="menu-title">PROJECTS</p>
      <!-- BEGIN EXAMPLE 1 -->
      <div class="status-widget">
        <div class="status-widget-wrapper">
          <div class="title">Project Title<a href="#" class="remove-widget"><i class="icon-custom-cross"></i></a></div>
          <p>Project Description</p>
        </div>
      </div>
      <!-- END EXAMPLE 1 -->
      <!-- END PROJECTS WIDGET -->
    </div>
    <div class="clearfix"></div>
    <!-- END SIDEBAR WIDGETS -->
  </div>
  </div>
  <!-- BEGIN SCROLL UP HOVER -->
  <a href="#" class="scrollup">Scroll</a>
  <!-- END SCROLL UP HOVER -->
  <!-- END MENU -->
  <!-- BEGIN SIDEBAR FOOTER WIDGET -->
  <div class="footer-widget">
    <div class="progress transparent progress-small no-radius no-margin">
      <div data-percentage="79%" class="progress-bar progress-bar-success animate-progress-bar"></div>
    </div>
    <div class="pull-right">
      <div class="details-status">
        <span data-animation-duration="560" data-value="86" class="animate-number"></span>%
      </div>
      <a href="#"><i class="fa fa-power-off"></i></a>
    </div>
  </div>
  <!-- END SIDEBAR FOOTER WIDGET -->
  <!-- END SIDEBAR -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= page_title %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Todo" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "app/application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="page-title">
        <h3><%= section_title %></h3>
      </div>
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Todo'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Todo'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= page_title %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Todo" %>">
    <%= stylesheet_link_tag "login", media: "all", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="error-body no-top lazy"  data-original="<%= image_url("work.jpg")%>"  style="background-image: url('<%= image_url("work.jpg")%>')">
<div class="container">
  <div class="row login-container animated fadeInUp">

        <div class="col-md-7 col-md-offset-2 tiles white no-padding">
     <div class="p-t-30 p-l-40 p-b-20 xs-p-t-10 xs-p-l-10 xs-p-b-10">

          <h2 class="normal">Ingresar al sistema</h2>
          <p>&nbsp;</p>
          <!--<p>Use Facebook, Twitter or your email to sign in.<br></p>
          <p class="p-b-20">Sign up Now! for webarch accounts, it's free and always will be..</p>-->
          <a href="<%= url_for login_path %>" class="btn btn-primary btn-cons" id="login_toggle">Entrar</a> o&nbsp;&nbsp;
          <a href="<%= url_for signup_path %>" class="btn btn-info btn-cons" id="register_toggle"> Crear una cuenta</a>
        </div>
    <div class="tiles grey p-t-20 p-b-20 text-black">

       <div class="row form-row m-l-20 m-r-20 xs-m-l-10 xs-m-r-10">
          <%= render 'layouts/messages' %>
          <%= yield %>
       </div>
    </div>
      </div>
  </div>
</div>
<!-- END CONTAINER -->
<%= javascript_include_tag "login/login", "data-turbolinks-track" => true %>
</body>



</html>